from ..helpers import add_to_repo
from ..helpers import check_solver_result

def test_pip_simple(root, provider, repo):
	root.add_dependency("rack", "*")

	add_to_repo(repo, "rack-mount", "0.4", deps={})
	add_to_repo(repo, "rack-mount", "0.5", deps={})
	add_to_repo(repo, "rack-mount", "0.5.1", deps={})
	add_to_repo(repo, "rack-mount", "0.5.2", deps={})
	add_to_repo(repo, "rack-mount", "0.6", deps={})
	add_to_repo(repo, "rack", "0.8", deps={})
	add_to_repo(repo, "rack", "0.9", deps={})
	add_to_repo(repo, "rack", "0.9.1", deps={})
	add_to_repo(repo, "rack", "0.9.2", deps={})
	add_to_repo(repo, "rack", "1.0", deps={})
	add_to_repo(repo, "rack", "1.1", deps={})
	add_to_repo(repo, "activemerchant", "1.2.3", deps={'activesupport': '>= 1.2.3'})
	add_to_repo(repo, "activemerchant", "2.2.3", deps={'activesupport': '>= 2.2.3'})
	add_to_repo(repo, "activemerchant", "2.3.5", deps={'activesupport': '>= 2.3.5'})
	add_to_repo(repo, "actionmailer", "1.2.3", deps={'actionmailer': '= 1.2.3', 'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionmailer", "2.2.3", deps={'actionmailer': '= 2.2.3', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionmailer", "2.3.5", deps={'actionmailer': '= 2.3.5', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta", deps={'actionmailer': '= 3.0.0-beta', 'activesupport': '= 3.0.0-beta'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta1", deps={'actionmailer': '= 3.0.0-beta1', 'activesupport': '= 3.0.0-beta1'})
	add_to_repo(repo, "railties", "1.2.3", deps={'activesupport': '= 1.2.3', 'actionpack': '= 1.2.3', 'actionmailer': '= 1.2.3', 'activerecord': '= 1.2.3'})
	add_to_repo(repo, "railties", "2.2.3", deps={'activesupport': '= 2.2.3', 'actionpack': '= 2.2.3', 'actionmailer': '= 2.2.3', 'activerecord': '= 2.2.3'})
	add_to_repo(repo, "railties", "2.3.5", deps={'activesupport': '= 2.3.5', 'actionpack': '= 2.3.5', 'actionmailer': '= 2.3.5', 'activerecord': '= 2.3.5'})
	add_to_repo(repo, "railties", "3.0.0-beta", deps={})
	add_to_repo(repo, "railties", "3.0.0-beta1", deps={})
	add_to_repo(repo, "nokogiri", "1.0", deps={})
	add_to_repo(repo, "nokogiri", "1.2", deps={})
	add_to_repo(repo, "nokogiri", "1.2.1", deps={})
	add_to_repo(repo, "nokogiri", "1.2.2", deps={})
	add_to_repo(repo, "nokogiri", "1.3", deps={})
	add_to_repo(repo, "nokogiri", "1.3.0-1", deps={})
	add_to_repo(repo, "nokogiri", "1.3.5", deps={})
	add_to_repo(repo, "nokogiri", "1.4.0", deps={})
	add_to_repo(repo, "nokogiri", "1.4.2", deps={})
	add_to_repo(repo, "weakling", "0.0.1", deps={})
	add_to_repo(repo, "weakling", "0.0.2", deps={})
	add_to_repo(repo, "weakling", "0.0.3", deps={})
	add_to_repo(repo, "activesupport", "1.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.3.5", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta1", deps={})
	add_to_repo(repo, "actionpack", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionpack", "2.2.3", deps={'rack': '~0.9.0', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionpack", "2.3.5", deps={'rack': '~1.0.0', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "actionpack", "3.0.0-beta", deps={'rack-mount': '>= 0.5', 'rack': '~1.1', 'activesupport': '= 3.0.0-beta'})
	add_to_repo(repo, "actionpack", "3.0.0-beta1", deps={'rack-mount': '>= 0.5', 'rack': '~1.1', 'activesupport': '= 3.0.0-beta1'})
	add_to_repo(repo, "activerecord", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "activerecord", "2.2.3", deps={'activesupport': '= 2.2.3'})
	add_to_repo(repo, "activerecord", "2.3.5", deps={'activesupport': '= 2.3.5'})
	add_to_repo(repo, "activerecord", "3.0.0-beta", deps={'activesupport': '= 3.0.0-beta', 'arel': '>= 0.2'})
	add_to_repo(repo, "activerecord", "3.0.0-beta1", deps={'activesupport': '= 3.0.0-beta1', 'arel': '>= 0.2'})
	add_to_repo(repo, "rails", "3.0.0-beta", deps={'activesupport': '= 3.0.0-beta', 'actionpack': '= 3.0.0-beta', 'actionmailer': '= 3.0.0-beta', 'activerecord': '= 3.0.0-beta', 'railties': '= 3.0.0-beta'})
	add_to_repo(repo, "rails", "3.0.0-beta1", deps={'activesupport': '= 3.0.0-beta1', 'actionpack': '= 3.0.0-beta1', 'actionmailer': '= 3.0.0-beta1', 'activerecord': '= 3.0.0-beta1', 'railties': '= 3.0.0-beta1'})

	check_solver_result(root, provider, {"rack": "1.1"})

def test_pip_swapping_children_with_successors(root, provider, repo):
	root.add_dependency("nginx", ">= 0.0.0")
	root.add_dependency("build-essential", ">= 0.0.0")

	add_to_repo(repo, "chef-handler", "1.3.0", deps={})
	add_to_repo(repo, "yum", "3.10.0", deps={})
	add_to_repo(repo, "windows", "1.39.2", deps={'chef-handler': '>= 0.0.0'})
	add_to_repo(repo, "windows", "0.0.4", deps={'chef-handler': '>= 0.0.0'})
	add_to_repo(repo, "windows", "0.0.3", deps={'chef-handler': '>= 0.0.0'})
	add_to_repo(repo, "windows", "0.0.2", deps={'chef-handler': '>= 0.0.0'})
	add_to_repo(repo, "windows", "0.0.1", deps={'chef-handler': '>= 0.0.0'})
	add_to_repo(repo, "build-essential", "3.2.0", deps={'seven_zip': '>= 0.0.0'})
	add_to_repo(repo, "build-essential", "2.4.0", deps={'7-zip': '>= 0.0.0'})
	add_to_repo(repo, "7-zip", "1.0.0", deps={'windows': '>= 1.2.2'})
	add_to_repo(repo, "nginx", "2.7.6", deps={'build-essential': '^2.0', 'yum-epel': '^1.3'})
	add_to_repo(repo, "nginx", "0.1.0", deps={'build-essential': '^2.0'})
	add_to_repo(repo, "nginx", "0.2.0", deps={'build-essential': '^2.0'})
	add_to_repo(repo, "seven_zip", "2.0.0", deps={'windows': '>= 1.2.2'})
	add_to_repo(repo, "yum-epel", "1.6.6", deps={'yum': '~3.10.0'})

	check_solver_result(root, provider, {"chef-handler": "1.3.0", "yum": "3.10.0", "windows": "1.39.2", "build-essential": "2.4.0", "yum-epel": "1.6.6", "nginx": "2.7.6", "7-zip": "1.0.0"})

def test_pip_contiguous_grouping(root, provider, repo):
	root.add_dependency("a", "*")
	root.add_dependency("b", "*")

	add_to_repo(repo, "a", "1.0.0", deps={})
	add_to_repo(repo, "a", "1.0.1", deps={'c': '>= 0.0.0'})
	add_to_repo(repo, "a", "1.0.2", deps={})
	add_to_repo(repo, "b", "1.0.0", deps={'a': '!= 1.0.2'})
	add_to_repo(repo, "c", "1.0.0", deps={})

	check_solver_result(root, provider, {"a": "1.0.1", "b": "1.0.0", "c": "1.0.0"})

def test_pip_empty(root, provider, repo):

	add_to_repo(repo, "rack-mount", "0.4", deps={})
	add_to_repo(repo, "rack-mount", "0.5", deps={})
	add_to_repo(repo, "rack-mount", "0.5.1", deps={})
	add_to_repo(repo, "rack-mount", "0.5.2", deps={})
	add_to_repo(repo, "rack-mount", "0.6", deps={})
	add_to_repo(repo, "rack", "0.8", deps={})
	add_to_repo(repo, "rack", "0.9", deps={})
	add_to_repo(repo, "rack", "0.9.1", deps={})
	add_to_repo(repo, "rack", "0.9.2", deps={})
	add_to_repo(repo, "rack", "1.0", deps={})
	add_to_repo(repo, "rack", "1.1", deps={})
	add_to_repo(repo, "activemerchant", "1.2.3", deps={'activesupport': '>= 1.2.3'})
	add_to_repo(repo, "activemerchant", "2.2.3", deps={'activesupport': '>= 2.2.3'})
	add_to_repo(repo, "activemerchant", "2.3.5", deps={'activesupport': '>= 2.3.5'})
	add_to_repo(repo, "actionmailer", "1.2.3", deps={'actionmailer': '= 1.2.3', 'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionmailer", "2.2.3", deps={'actionmailer': '= 2.2.3', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionmailer", "2.3.5", deps={'actionmailer': '= 2.3.5', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta", deps={'actionmailer': '= 3.0.0-beta', 'activesupport': '= 3.0.0-beta'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta1", deps={'actionmailer': '= 3.0.0-beta1', 'activesupport': '= 3.0.0-beta1'})
	add_to_repo(repo, "railties", "1.2.3", deps={'activesupport': '= 1.2.3', 'actionpack': '= 1.2.3', 'actionmailer': '= 1.2.3', 'activerecord': '= 1.2.3'})
	add_to_repo(repo, "railties", "2.2.3", deps={'activesupport': '= 2.2.3', 'actionpack': '= 2.2.3', 'actionmailer': '= 2.2.3', 'activerecord': '= 2.2.3'})
	add_to_repo(repo, "railties", "2.3.5", deps={'activesupport': '= 2.3.5', 'actionpack': '= 2.3.5', 'actionmailer': '= 2.3.5', 'activerecord': '= 2.3.5'})
	add_to_repo(repo, "railties", "3.0.0-beta", deps={})
	add_to_repo(repo, "railties", "3.0.0-beta1", deps={})
	add_to_repo(repo, "nokogiri", "1.0", deps={})
	add_to_repo(repo, "nokogiri", "1.2", deps={})
	add_to_repo(repo, "nokogiri", "1.2.1", deps={})
	add_to_repo(repo, "nokogiri", "1.2.2", deps={})
	add_to_repo(repo, "nokogiri", "1.3", deps={})
	add_to_repo(repo, "nokogiri", "1.3.0-1", deps={})
	add_to_repo(repo, "nokogiri", "1.3.5", deps={})
	add_to_repo(repo, "nokogiri", "1.4.0", deps={})
	add_to_repo(repo, "nokogiri", "1.4.2", deps={})
	add_to_repo(repo, "weakling", "0.0.1", deps={})
	add_to_repo(repo, "weakling", "0.0.2", deps={})
	add_to_repo(repo, "weakling", "0.0.3", deps={})
	add_to_repo(repo, "activesupport", "1.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.3.5", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta1", deps={})
	add_to_repo(repo, "actionpack", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionpack", "2.2.3", deps={'rack': '~0.9.0', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionpack", "2.3.5", deps={'rack': '~1.0.0', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "actionpack", "3.0.0-beta", deps={'rack-mount': '>= 0.5', 'rack': '~1.1', 'activesupport': '= 3.0.0-beta'})
	add_to_repo(repo, "actionpack", "3.0.0-beta1", deps={'rack-mount': '>= 0.5', 'rack': '~1.1', 'activesupport': '= 3.0.0-beta1'})
	add_to_repo(repo, "activerecord", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "activerecord", "2.2.3", deps={'activesupport': '= 2.2.3'})
	add_to_repo(repo, "activerecord", "2.3.5", deps={'activesupport': '= 2.3.5'})
	add_to_repo(repo, "activerecord", "3.0.0-beta", deps={'activesupport': '= 3.0.0-beta', 'arel': '>= 0.2'})
	add_to_repo(repo, "activerecord", "3.0.0-beta1", deps={'activesupport': '= 3.0.0-beta1', 'arel': '>= 0.2'})
	add_to_repo(repo, "rails", "3.0.0-beta", deps={'activesupport': '= 3.0.0-beta', 'actionpack': '= 3.0.0-beta', 'actionmailer': '= 3.0.0-beta', 'activerecord': '= 3.0.0-beta', 'railties': '= 3.0.0-beta'})
	add_to_repo(repo, "rails", "3.0.0-beta1", deps={'activesupport': '= 3.0.0-beta1', 'actionpack': '= 3.0.0-beta1', 'actionmailer': '= 3.0.0-beta1', 'activerecord': '= 3.0.0-beta1', 'railties': '= 3.0.0-beta1'})

	check_solver_result(root, provider, {})

def test_pip_simple_with_shared_dependencies(root, provider, repo):
	root.add_dependency("actionpack", "*")
	root.add_dependency("activerecord", "2.3.5")

	add_to_repo(repo, "rack-mount", "0.4", deps={})
	add_to_repo(repo, "rack-mount", "0.5", deps={})
	add_to_repo(repo, "rack-mount", "0.5.1", deps={})
	add_to_repo(repo, "rack-mount", "0.5.2", deps={})
	add_to_repo(repo, "rack-mount", "0.6", deps={})
	add_to_repo(repo, "rack", "0.8", deps={})
	add_to_repo(repo, "rack", "0.9", deps={})
	add_to_repo(repo, "rack", "0.9.1", deps={})
	add_to_repo(repo, "rack", "0.9.2", deps={})
	add_to_repo(repo, "rack", "1.0", deps={})
	add_to_repo(repo, "rack", "1.1", deps={})
	add_to_repo(repo, "activemerchant", "1.2.3", deps={'activesupport': '>= 1.2.3'})
	add_to_repo(repo, "activemerchant", "2.2.3", deps={'activesupport': '>= 2.2.3'})
	add_to_repo(repo, "activemerchant", "2.3.5", deps={'activesupport': '>= 2.3.5'})
	add_to_repo(repo, "actionmailer", "1.2.3", deps={'actionmailer': '= 1.2.3', 'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionmailer", "2.2.3", deps={'actionmailer': '= 2.2.3', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionmailer", "2.3.5", deps={'actionmailer': '= 2.3.5', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta", deps={'actionmailer': '= 3.0.0-beta', 'activesupport': '= 3.0.0-beta'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta1", deps={'actionmailer': '= 3.0.0-beta1', 'activesupport': '= 3.0.0-beta1'})
	add_to_repo(repo, "railties", "1.2.3", deps={'activesupport': '= 1.2.3', 'actionpack': '= 1.2.3', 'actionmailer': '= 1.2.3', 'activerecord': '= 1.2.3'})
	add_to_repo(repo, "railties", "2.2.3", deps={'activesupport': '= 2.2.3', 'actionpack': '= 2.2.3', 'actionmailer': '= 2.2.3', 'activerecord': '= 2.2.3'})
	add_to_repo(repo, "railties", "2.3.5", deps={'activesupport': '= 2.3.5', 'actionpack': '= 2.3.5', 'actionmailer': '= 2.3.5', 'activerecord': '= 2.3.5'})
	add_to_repo(repo, "railties", "3.0.0-beta", deps={})
	add_to_repo(repo, "railties", "3.0.0-beta1", deps={})
	add_to_repo(repo, "nokogiri", "1.0", deps={})
	add_to_repo(repo, "nokogiri", "1.2", deps={})
	add_to_repo(repo, "nokogiri", "1.2.1", deps={})
	add_to_repo(repo, "nokogiri", "1.2.2", deps={})
	add_to_repo(repo, "nokogiri", "1.3", deps={})
	add_to_repo(repo, "nokogiri", "1.3.0-1", deps={})
	add_to_repo(repo, "nokogiri", "1.3.5", deps={})
	add_to_repo(repo, "nokogiri", "1.4.0", deps={})
	add_to_repo(repo, "nokogiri", "1.4.2", deps={})
	add_to_repo(repo, "weakling", "0.0.1", deps={})
	add_to_repo(repo, "weakling", "0.0.2", deps={})
	add_to_repo(repo, "weakling", "0.0.3", deps={})
	add_to_repo(repo, "activesupport", "1.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.3.5", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta1", deps={})
	add_to_repo(repo, "actionpack", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionpack", "2.2.3", deps={'rack': '~0.9.0', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionpack", "2.3.5", deps={'rack': '~1.0.0', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "actionpack", "3.0.0-beta", deps={'rack-mount': '>= 0.5', 'rack': '~1.1', 'activesupport': '= 3.0.0-beta'})
	add_to_repo(repo, "actionpack", "3.0.0-beta1", deps={'rack-mount': '>= 0.5', 'rack': '~1.1', 'activesupport': '= 3.0.0-beta1'})
	add_to_repo(repo, "activerecord", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "activerecord", "2.2.3", deps={'activesupport': '= 2.2.3'})
	add_to_repo(repo, "activerecord", "2.3.5", deps={'activesupport': '= 2.3.5'})
	add_to_repo(repo, "activerecord", "3.0.0-beta", deps={'activesupport': '= 3.0.0-beta', 'arel': '>= 0.2'})
	add_to_repo(repo, "activerecord", "3.0.0-beta1", deps={'activesupport': '= 3.0.0-beta1', 'arel': '>= 0.2'})
	add_to_repo(repo, "rails", "3.0.0-beta", deps={'activesupport': '= 3.0.0-beta', 'actionpack': '= 3.0.0-beta', 'actionmailer': '= 3.0.0-beta', 'activerecord': '= 3.0.0-beta', 'railties': '= 3.0.0-beta'})
	add_to_repo(repo, "rails", "3.0.0-beta1", deps={'activesupport': '= 3.0.0-beta1', 'actionpack': '= 3.0.0-beta1', 'actionmailer': '= 3.0.0-beta1', 'activerecord': '= 3.0.0-beta1', 'railties': '= 3.0.0-beta1'})

	check_solver_result(root, provider, {"actionpack": "2.3.5", "activesupport": "2.3.5", "rack": "1.0", "activerecord": "2.3.5"})

def test_pip_previous_conflict(root, provider, repo):
	root.add_dependency("a", "*")
	root.add_dependency("b", "*")

	add_to_repo(repo, "a", "0.3.0", deps={'c': '~1.4', 'e': '~1.4'})
	add_to_repo(repo, "a", "0.2.0", deps={'c': '~1.3', 'e': '~1.4'})
	add_to_repo(repo, "a", "0.1.0", deps={'c': '>= 0', 'f': '~1.4', 'e': '~1.0'})
	add_to_repo(repo, "c", "2.0.0", deps={'d': '~2.0.0'})
	add_to_repo(repo, "c", "1.4.0", deps={'d': '~1.4'})
	add_to_repo(repo, "f", "1.4.0", deps={'e': '~2.0'})
	add_to_repo(repo, "d", "1.4.0", deps={})
	add_to_repo(repo, "d", "2.0.0", deps={})
	add_to_repo(repo, "e", "2.0.0", deps={'d': '> 1, < 3'})
	add_to_repo(repo, "e", "1.4.0", deps={'d': '> 1, < 3'})
	add_to_repo(repo, "e", "1.0.0", deps={})
	add_to_repo(repo, "b", "2.0.0", deps={'c': '= 2.0.0', 'd': '~2.0'})
	add_to_repo(repo, "b", "1.4.0", deps={'c': '= 1.4.0', 'd': '~1.4'})

	check_solver_result(root, provider, {"a": "0.3.0", "c": "1.4.0", "e": "1.4.0", "d": "1.4.0", "b": "1.4.0"})

def test_pip_conflict_on_child(root, provider, repo):
	root.add_dependency("chef-app", "*")

	add_to_repo(repo, "chef-app", "1.0.0", deps={'chef': '~10.26', 'berkshelf': '~2.0'})
	add_to_repo(repo, "chef", "10.26.0", deps={'json': '<= 1.7.7, >= 1.4.4'})
	add_to_repo(repo, "berkshelf", "2.0.7", deps={'json': '>= 1.7.7'})
	add_to_repo(repo, "json", "1.6.5", deps={})
	add_to_repo(repo, "json", "1.7.7", deps={})
	add_to_repo(repo, "json", "1.8.0", deps={})

	check_solver_result(root, provider, {"chef-app": "1.0.0", "chef": "10.26.0", "berkshelf": "2.0.7", "json": "1.7.7"})


def test_pip_conflict(root, provider, repo):
	root.add_dependency("my-app", "*")

	add_to_repo(repo, "my-app", "1.0.0", deps={'activemodel': '>= 0', 'grape': '>= 0'})
	add_to_repo(repo, "activemodel", "3.2.8", deps={'builder': '~3.0.0'})
	add_to_repo(repo, "activemodel", "3.2.9", deps={'builder': '~3.0.0'})
	add_to_repo(repo, "activemodel", "3.2.10", deps={'builder': '~3.0.0'})
	add_to_repo(repo, "activemodel", "3.2.11", deps={'builder': '~3.0.0'})
	add_to_repo(repo, "builder", "3.0.4", deps={})
	add_to_repo(repo, "builder", "3.1.4", deps={})
	add_to_repo(repo, "grape", "0.2.6", deps={'builder': '>= 0'})

	check_solver_result(root, provider, {"activemodel": "3.2.11", "my-app": "1.0.0", "builder": "3.0.4", "grape": "0.2.6"})

def test_pip_root_conflict_on_child(root, provider, repo):
	root.add_dependency("activesupport", "~3.0")
	root.add_dependency("i18n", "~0.4")
	root.add_dependency("activerecord", "~3.0")
	root.add_dependency("builder", "~2.1.2")

	add_to_repo(repo, "activemodel", "3.0.5", deps={'activesupport': '= 3.0.5', 'builder': '~2.1.2', 'i18n': '~0.4'})
	add_to_repo(repo, "activemodel", "3.0.0", deps={'activesupport': '= 3.0.0', 'builder': '~2.1.2', 'i18n': '~0.4.1'})
	add_to_repo(repo, "activemodel", "3.1.3", deps={'activesupport': '= 3.1.3', 'builder': '~2.1.2', 'i18n': '~0.5'})
	add_to_repo(repo, "activesupport", "3.0.0", deps={})
	add_to_repo(repo, "activesupport", "3.0.1", deps={})
	add_to_repo(repo, "activesupport", "3.0.5", deps={})
	add_to_repo(repo, "activesupport", "3.1.7", deps={})
	add_to_repo(repo, "builder", "2.1.2", deps={})
	add_to_repo(repo, "builder", "3.0.1", deps={})
	add_to_repo(repo, "builder", "3.1.3", deps={})
	add_to_repo(repo, "activerecord", "3.0.0", deps={'activemodel': '= 3.0.0', 'activesupport': '= 3.0.0'})
	add_to_repo(repo, "activerecord", "3.0.5", deps={'activemodel': '= 3.0.5', 'activesupport': '= 3.0.5'})
	add_to_repo(repo, "activerecord", "3.0.9", deps={'activemodel': '= 3.1.5', 'activesupport': '= 3.1.5'})
	add_to_repo(repo, "i18n", "0.4.1", deps={})
	add_to_repo(repo, "i18n", "0.4.2", deps={})

	check_solver_result(root, provider, {"activemodel": "3.0.5", "activesupport": "3.0.5", "i18n": "0.4.2", "activerecord": "3.0.5", "builder": "2.1.2"})

def test_pip_previous_primary_conflict(root, provider, repo):
	root.add_dependency("a", ">= 4.2")
	root.add_dependency("b", "< 5.1")

	add_to_repo(repo, "a", "5.1.0", deps={})
	add_to_repo(repo, "a", "5.0.5", deps={'c': '*'})
	add_to_repo(repo, "a", "5.0.4", deps={})
	add_to_repo(repo, "a", "4.0.3", deps={'c': '*'})
	add_to_repo(repo, "a", "4.0.2", deps={})
	add_to_repo(repo, "a", "4.0.1", deps={'c': '*'})
	add_to_repo(repo, "b", "5.1.0", deps={'a': '= 5.1.0'})
	add_to_repo(repo, "b", "5.0.5", deps={'a': '= 5.0.5'})
	add_to_repo(repo, "b", "5.0.4", deps={'a': '= 5.0.4'})
	add_to_repo(repo, "c", "1.0.0", deps={})

	check_solver_result(root, provider, {"a": "5.0.5", "c": "1.0.0", "b": "5.0.5"})

def test_pip_complex_conflict(root, provider, repo):
	root.add_dependency("my-app", "*")

	add_to_repo(repo, "a", "1.0.2", deps={'d': '>= 0'})
	add_to_repo(repo, "a", "1.1.4", deps={'d': '>= 0'})
	add_to_repo(repo, "a", "1.2.0", deps={'d': '>= 0'})
	add_to_repo(repo, "a", "1.4.0", deps={'d': '>= 0'})
	add_to_repo(repo, "b", "0.3.4", deps={'a': '>= 1.5.0'})
	add_to_repo(repo, "b", "0.3.5", deps={'a': '>= 1.2'})
	add_to_repo(repo, "b", "0.3.3", deps={'a': '> 1.0'})
	add_to_repo(repo, "my-app", "1.3.0", deps={'c': '>= 4.0', 'b': '>= 0'})
	add_to_repo(repo, "my-app", "1.2.0", deps={'c': '~3.3.0', 'b': '= 0.3.4'})
	add_to_repo(repo, "my-app", "1.1.0", deps={'c': '~3.2.0', 'b': '= 0.3.5'})
	add_to_repo(repo, "d", "1.3.0", deps={'x': '>= 0'})
	add_to_repo(repo, "d", "1.4.1", deps={'x': '>= 0'})
	add_to_repo(repo, "d", "0.9.8", deps={})
	add_to_repo(repo, "c", "3.2", deps={'a': '^1.0'})
	add_to_repo(repo, "c", "3.3", deps={'a': '^1.0'})

	check_solver_result(root, provider, {"a": "1.4.0", "b": "0.3.5", "my-app": "1.1.0", "d": "0.9.8", "c": "3.2"})

def test_pip_simple_speed_test(root, provider, repo):
	root.add_dependency("menu", ">= 1.0.0")
	root.add_dependency("icons", "1.0.0")

	add_to_repo(repo, "dropdown", "2.3.0", deps={'icons': '2.0.0'})
	add_to_repo(repo, "dropdown", "2.2.0", deps={'icons': '2.0.0'})
	add_to_repo(repo, "dropdown", "2.1.0", deps={'icons': '2.0.0'})
	add_to_repo(repo, "dropdown", "2.0.0", deps={'icons': '2.0.0'})
	add_to_repo(repo, "dropdown", "1.8.0", deps={})
	add_to_repo(repo, "menu", "1.5.0", deps={'dropdown': '>= 2.0.0'})
	add_to_repo(repo, "menu", "1.4.0", deps={'dropdown': '>= 2.0.0'})
	add_to_repo(repo, "menu", "1.3.0", deps={'dropdown': '>= 2.0.0'})
	add_to_repo(repo, "menu", "1.2.0", deps={'dropdown': '>= 2.0.0'})
	add_to_repo(repo, "menu", "1.1.0", deps={'dropdown': '>= 2.0.0'})
	add_to_repo(repo, "menu", "1.0.0", deps={'dropdown': '1.8.0'})
	add_to_repo(repo, "icons", "2.0.0", deps={})
	add_to_repo(repo, "icons", "1.0.0", deps={})

	check_solver_result(root, provider, {"dropdown": "1.8.0", "menu": "1.0.0", "icons": "1.0.0"})

def test_pip_overlap(root, provider, repo):
	root.add_dependency("a", "1.0.0")
	root.add_dependency("b", "1.0.0")

	add_to_repo(repo, "a", "1.0.0", deps={'shared': '< 4.0.0'})
	add_to_repo(repo, "b", "1.0.0", deps={'shared': '< 5.0.0'})
	add_to_repo(repo, "shared", "2.0.0", deps={})
	add_to_repo(repo, "shared", "3.0.0", deps={})
	add_to_repo(repo, "shared", "3.6.9", deps={})
	add_to_repo(repo, "shared", "4.0.0", deps={})
	add_to_repo(repo, "shared", "5.0.0", deps={})

	check_solver_result(root, provider, {"a": "1.0.0", "shared": "3.6.9", "b": "1.0.0"})

def test_pip_simple_with_dependencies(root, provider, repo):
	root.add_dependency("actionpack", "*")

	add_to_repo(repo, "rack-mount", "0.4", deps={})
	add_to_repo(repo, "rack-mount", "0.5", deps={})
	add_to_repo(repo, "rack-mount", "0.5.1", deps={})
	add_to_repo(repo, "rack-mount", "0.5.2", deps={})
	add_to_repo(repo, "rack-mount", "0.6", deps={})
	add_to_repo(repo, "rack", "0.8", deps={})
	add_to_repo(repo, "rack", "0.9", deps={})
	add_to_repo(repo, "rack", "0.9.1", deps={})
	add_to_repo(repo, "rack", "0.9.2", deps={})
	add_to_repo(repo, "rack", "1.0", deps={})
	add_to_repo(repo, "rack", "1.1", deps={})
	add_to_repo(repo, "activemerchant", "1.2.3", deps={'activesupport': '>= 1.2.3'})
	add_to_repo(repo, "activemerchant", "2.2.3", deps={'activesupport': '>= 2.2.3'})
	add_to_repo(repo, "activemerchant", "2.3.5", deps={'activesupport': '>= 2.3.5'})
	add_to_repo(repo, "actionmailer", "1.2.3", deps={'actionmailer': '= 1.2.3', 'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionmailer", "2.2.3", deps={'actionmailer': '= 2.2.3', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionmailer", "2.3.5", deps={'actionmailer': '= 2.3.5', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta", deps={'actionmailer': '= 3.0.0-beta', 'activesupport': '= 3.0.0-beta'})
	add_to_repo(repo, "actionmailer", "3.0.0-beta1", deps={'actionmailer': '= 3.0.0-beta1', 'activesupport': '= 3.0.0-beta1'})
	add_to_repo(repo, "railties", "1.2.3", deps={'activesupport': '= 1.2.3', 'actionpack': '= 1.2.3', 'actionmailer': '= 1.2.3', 'activerecord': '= 1.2.3'})
	add_to_repo(repo, "railties", "2.2.3", deps={'activesupport': '= 2.2.3', 'actionpack': '= 2.2.3', 'actionmailer': '= 2.2.3', 'activerecord': '= 2.2.3'})
	add_to_repo(repo, "railties", "2.3.5", deps={'activesupport': '= 2.3.5', 'actionpack': '= 2.3.5', 'actionmailer': '= 2.3.5', 'activerecord': '= 2.3.5'})
	add_to_repo(repo, "railties", "3.0.0-beta", deps={})
	add_to_repo(repo, "railties", "3.0.0-beta1", deps={})
	add_to_repo(repo, "nokogiri", "1.0", deps={})
	add_to_repo(repo, "nokogiri", "1.2", deps={})
	add_to_repo(repo, "nokogiri", "1.2.1", deps={})
	add_to_repo(repo, "nokogiri", "1.2.2", deps={})
	add_to_repo(repo, "nokogiri", "1.3", deps={})
	add_to_repo(repo, "nokogiri", "1.3.0-1", deps={})
	add_to_repo(repo, "nokogiri", "1.3.5", deps={})
	add_to_repo(repo, "nokogiri", "1.4.0", deps={})
	add_to_repo(repo, "nokogiri", "1.4.2", deps={})
	add_to_repo(repo, "weakling", "0.0.1", deps={})
	add_to_repo(repo, "weakling", "0.0.2", deps={})
	add_to_repo(repo, "weakling", "0.0.3", deps={})
	add_to_repo(repo, "activesupport", "1.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.2.3", deps={})
	add_to_repo(repo, "activesupport", "2.3.5", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta", deps={})
	add_to_repo(repo, "activesupport", "3.0.0-beta1", deps={})
	add_to_repo(repo, "actionpack", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "actionpack", "2.2.3", deps={'rack': '~0.9.0', 'activesupport': '= 2.2.3'})
	add_to_repo(repo, "actionpack", "2.3.5", deps={'rack': '~1.0.0', 'activesupport': '= 2.3.5'})
	add_to_repo(repo, "activerecord", "1.2.3", deps={'activesupport': '= 1.2.3'})
	add_to_repo(repo, "activerecord", "2.2.3", deps={'activesupport': '= 2.2.3'})
	add_to_repo(repo, "activerecord", "2.3.5", deps={'activesupport': '= 2.3.5'})

	check_solver_result(root, provider, {"actionpack": "2.3.5", "activesupport": "2.3.5", "rack": "1.0"})

def test_pip_three_way_conflict(root, provider, repo):
	root.add_dependency("afoauth2client", "*")
	root.add_dependency("afamazons3client", "*")
	root.add_dependency("cargobay", "*")

	add_to_repo(repo, "afoauth2client", "0.1.2", deps={'afnetworking': '^1.3'})
	add_to_repo(repo, "afoauth2client", "0.1.1", deps={'afnetworking': '^1.0'})
	add_to_repo(repo, "afoauth2client", "0.1.0", deps={'afnetworking': '^1.0'})
	add_to_repo(repo, "afoauth2client", "0.0.1", deps={'afnetworking': '^1.0'})
	add_to_repo(repo, "afamazons3client", "2.0.0", deps={'afnetworking': '^2.0'})
	add_to_repo(repo, "afamazons3client", "1.0.1", deps={'afnetworking': '^1.3'})
	add_to_repo(repo, "afamazons3client", "0.3.0", deps={'afnetworking': '^1.0'})
	add_to_repo(repo, "afamazons3client", "0.2.0", deps={'afnetworking': '^1.0'})
	add_to_repo(repo, "afamazons3client", "0.1.0", deps={'afnetworking': '^1.0'})
	add_to_repo(repo, "cargobay", "2.1.0", deps={'afnetworking': '^2.2'})
	add_to_repo(repo, "cargobay", "2.0.3", deps={'afnetworking': '^2.1'})
	add_to_repo(repo, "cargobay", "2.0.2", deps={'afnetworking': '^2.0'})
	add_to_repo(repo, "cargobay", "2.0.1", deps={'afnetworking': '^2.0'})
	add_to_repo(repo, "cargobay", "2.0.0", deps={'afnetworking': '^2.0'})
	add_to_repo(repo, "cargobay", "1.0.0", deps={'afnetworking': '^1.0'})
	add_to_repo(repo, "cargobay", "0.3.3", deps={'afnetworking': '>= 1.0'})
	add_to_repo(repo, "cargobay", "0.3.2", deps={'afnetworking': '>= 1.0'})
	add_to_repo(repo, "cargobay", "0.3.1", deps={'afnetworking': '>= 1.0'})
	add_to_repo(repo, "cargobay", "0.3.0", deps={'afnetworking': '>= 1.0'})
	add_to_repo(repo, "cargobay", "0.2.1", deps={'afnetworking': '>= 0.9'})
	add_to_repo(repo, "cargobay", "0.2.0", deps={'afnetworking': '>= 0.9'})
	add_to_repo(repo, "cargobay", "0.1.0", deps={'afnetworking': '>= 0.9'})
	add_to_repo(repo, "afnetworking", "2.5.0", deps={})
	add_to_repo(repo, "afnetworking", "2.4.1", deps={})
	add_to_repo(repo, "afnetworking", "2.4.0", deps={})
	add_to_repo(repo, "afnetworking", "2.3.1", deps={})
	add_to_repo(repo, "afnetworking", "2.3.0", deps={})
	add_to_repo(repo, "afnetworking", "2.2.4", deps={})
	add_to_repo(repo, "afnetworking", "2.2.3", deps={})
	add_to_repo(repo, "afnetworking", "2.2.2", deps={})
	add_to_repo(repo, "afnetworking", "2.2.1", deps={})
	add_to_repo(repo, "afnetworking", "2.2.0", deps={})
	add_to_repo(repo, "afnetworking", "2.1.0", deps={})
	add_to_repo(repo, "afnetworking", "2.0.3", deps={})
	add_to_repo(repo, "afnetworking", "2.0.2", deps={})
	add_to_repo(repo, "afnetworking", "2.0.1", deps={})
	add_to_repo(repo, "afnetworking", "2.0.0", deps={})
	add_to_repo(repo, "afnetworking", "1.3.4", deps={})
	add_to_repo(repo, "afnetworking", "1.3.3", deps={})
	add_to_repo(repo, "afnetworking", "1.3.2", deps={})
	add_to_repo(repo, "afnetworking", "1.3.1", deps={})
	add_to_repo(repo, "afnetworking", "1.3.0", deps={})
	add_to_repo(repo, "afnetworking", "1.2.1", deps={})
	add_to_repo(repo, "afnetworking", "1.2.0", deps={})
	add_to_repo(repo, "afnetworking", "1.1.0", deps={})
	add_to_repo(repo, "afnetworking", "1.0.1", deps={})
	add_to_repo(repo, "afnetworking", "1.0", deps={})
	add_to_repo(repo, "afnetworking", "0.10.1", deps={})
	add_to_repo(repo, "afnetworking", "0.10.0", deps={})
	add_to_repo(repo, "afnetworking", "0.9.2", deps={})
	add_to_repo(repo, "afnetworking", "0.9.1", deps={})
	add_to_repo(repo, "afnetworking", "0.9.0", deps={})
	add_to_repo(repo, "afnetworking", "0.7.0", deps={'jsonkit': '>= 0'})
	add_to_repo(repo, "afnetworking", "0.5.1", deps={'jsonkit': '>= 0'})

	check_solver_result(root, provider, {"afoauth2client": "0.1.2", "afamazons3client": "1.0.1", "cargobay": "1.0.0", "afnetworking": "1.3.4"})
